spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}502176f14e884ddcb47b64ec3b738186fbb51d791e97ea7c8c8ed99572a5bac4'

token:
  expiration_time: 864000000
  secret: user_token_native_user_service_default

gateway:
  ip: 172.30.1.26

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders
